version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "suggestify-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-170fp3h5r68n3"
s3_prefix = "suggestify-serverless"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
