AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
    StageName:
        Type: String
        Default: prod

Resources:
    # Suggestions Lambda
    SuggestifyFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./build/suggestions
            Handler: index.handler
            Runtime: nodejs14.x
            MemorySize: 128
            Timeout: 10
            Events:
                GetSuggestions:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref HttpApi
                        Method: GET
                        Path: /suggestions
            Policies:
                - AWSLambdaBasicExecutionRole

    # Events callback Lambda
    EventsLogFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            CodeUri: ./build/events
            Runtime: nodejs14.x
            MemorySize: 128
            Timeout: 10
            Events:
                PostEvent:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref HttpApi
                        Method: POST
                        Path: /events
            Policies:
                - AWSLambdaBasicExecutionRole

    # API Gateway
    HttpApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            StageName: !Ref StageName
            CorsConfiguration:
                AllowOrigins:
                    - "http://localhost:3000"
                    - "http://localhost:8080"
                AllowMethods:
                    - GET
                    - OPTIONS
                    - POST
                MaxAge: 1800

    # Logs
    AccessLogs:
        Type: AWS::Logs::LogGroup
        Properties:
            RetentionInDays: 7

Outputs:
    HttpApiUrl:
        Description: URL of your API endpoint
        Value:
            Fn::Sub: "https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/"
    HttpApiId:
        Description: Api id of HttpApi
        Value:
            Ref: HttpApi
